「ヒューリスティック調査」を追加
kufu/product-design pull request #138
Opened 2023-04-20 10:51 UTC by wentzzz

AIで出力したものを調整しています

2023-04-20 10:56 UTC, wentzzz commented on src/pages/wiki/documents/heuristic-study.md
> +> - 10：ヘルプとドキュメントの提供
引用を表現したいけどいい記法が思いつかない…

2023-04-21 05:13 UTC, uknmr reviewed
全体的に Markdown から HTML に変換した際、文と文の間に意図しない余白が入ってそうです。

末尾に2スペースで改行を入れるか、段落を分けるか対応をお願いします!

2023-04-21 05:13 UTC, uknmr commented on src/pages/wiki/documents/heuristic-study.md
> +調査はプロダクト開発サイクルの初期段階や、大きな変更があった際に実施されることが多く、発見された問題の改善することで製品の品質やユーザーの満足度の向上が期待される。
> 発見された問題を改善することで製品の品質やユーザーの満足度の向上が期待される。

何も言ってないに近い印象を受けた🤣

あと誤字

```suggestion
調査はプロダクト開発サイクルの初期段階や、大きな変更があった際に実施されることが多く、発見された問題を改善することで製品の品質やユーザーの満足度の向上が期待される。
```

2023-05-19 04:08 UTC, kgsi commented on src/pages/wiki/documents/heuristic-study.md
> +> - 10：ヘルプとドキュメントの提供
@wentzzz コード記述にしちゃうとかでどうですか？

2023-05-22 01:47 UTC, kgsi approved these changes
LGTM!

2023-05-22 02:35 UTC, uknmr requested changes

2023-05-22 02:35 UTC, uknmr commented on src/pages/wiki/documents/heuristic-study.md
> +via: [10 Usability Heuristics for User Interface Design | Nielsen Norman Group](https://www.nngroup.com/articles/ten-usability-heuristics/)
`pre > code` ではなくリストで良さそうだった。
リンクもまとめてみた。

```suggestion
和訳した「[10 Usability Heuristics for User Interface Design](https://www.nngroup.com/articles/ten-usability-heuristics/)」は次の通り。  

## ユーザーインターフェースデザインのための10のユーザビリティヒューリスティック原則
- 1：システム状態の可視性
- 2：システムと現実世界との一致
- 3：ユーザーの操作と自由度
- 4：一貫性と標準化
- 5：エラーの防止
- 6：記憶よりも認識
- 7：柔軟性と効率性の両立
- 8：美的かつ最小限のデザイン
- 9：ユーザーがエラーを認識、診断、回復できるように支援する
- 10：ヘルプとドキュメントの提供
```

2023-05-22 02:35 UTC, uknmr commented on src/pages/wiki/documents/heuristic-study.md
> +- [10 Usability Heuristics for User Interface Design | Nielsen Norman Group](https://www.nngroup.com/articles/ten-usability-heuristics/)
文中にあれば参考になくても良さそう。

```suggestion
```

2023-05-22 02:35 UTC, uknmr commented on src/pages/wiki/documents/heuristic-study.md
> +調査はプロダクト開発サイクルの初期段階や、大きな変更があった際に実施されることが多く、発見された問題を改善することで製品の品質やユーザーの満足度の向上が期待される。
文が長く理解しにくそうだったので、文を分けた。

```suggestion
調査はプロダクト開発サイクルの初期段階や、大きな変更があった際に実施されることが多い。発見された問題を改善により製品の品質やユーザー満足度の向上を期待できる。  
```

2023-05-22 02:35 UTC, uknmr commented on src/pages/wiki/documents/heuristic-study.md
> +プロダクト開発においては、ユーザビリティの原則に基づいて、製品の使いやすさや効率性を評価し、ヒューリスティック原則としては、一貫性と標準化、フィードバックの可視性、認知負荷の軽減などが挙げられる。
文章として「ユーザビリティ原則に基づいて評価し、ヒューリスティック原則としては挙げられる」って日本語として成り立ってなさそうです。

直してみましたが、本来書こうとした文書見えないので修正をお願いします。

```suggestion
プロダクト開発においては、ユーザビリティの原則に基づいて製品の使いやすさや効率性を評価し、ヒューリスティック原則に基づいて一貫性と標準化、フィードバックの可視性、認知負荷の軽減などを評価する。
```

2023-05-26 05:01 UTC, wentzzz commented on src/pages/wiki/documents/heuristic-study.md
> +プロダクト開発においては、ユーザビリティの原則に基づいて、製品の使いやすさや効率性を評価し、ヒューリスティック原則としては、一貫性と標準化、フィードバックの可視性、認知負荷の軽減などが挙げられる。
どこかで文章が崩れたみたいなので、書き直しました！

2023-05-26 05:38 UTC, uknmr approved these changes
LGTM~!

2023-05-26 05:38 UTC, merged