「点字キーボード」を追加
kufu/product-design pull request #199
Opened 2023-06-08 11:01 UTC by kgsi

2023-06-08 11:20 UTC, uknmr requested changes
辻さんにレビュー依頼するといいかも。

2023-06-08 11:20 UTC, uknmr commented on src/pages/wiki/documents/braille-keyboard.md
> +点字キーボードとは、視覚障害者がデバイスを操作するために使用する特別なタイプのキーボードのこと。点字キーボードとも呼ばれる。
```suggestion
点字キーボードとは、視覚障害者がデバイスを操作するために使用する特別なタイプのキーボードのこと。
```

2023-06-08 11:20 UTC, uknmr commented on src/pages/wiki/documents/braille-keyboard.md
> +一般的に点字キーボードは通常のキーボードとは異なり、一部のモデルでは、各点字文字を作成するための6つのキー（通常、各キーは点字セルの特定の点を表す）と、スペースキー、エンターキー、バックスペースキーなどの追加機能キーがある。
一般的なのか一部のモデルなのかｗ

```suggestion
一般的に点字キーボードは通常のキーボードとは異なり、各点字文字を作成するための6つのキー（通常、各キーは点字セルの特定の点を表す）と、スペースキー、エンターキー、バックスペースキーなどの追加機能キーがある。
```

2023-06-08 11:20 UTC, uknmr commented on src/pages/wiki/documents/braille-keyboard.md
> +一般的に点字キーボードは通常のキーボードとは異なり、一部のモデルでは、各点字文字を作成するための6つのキー（通常、各キーは点字セルの特定の点を表す）と、スペースキー、エンターキー、バックスペースキーなどの追加機能キーがある。
情報の真偽わかりません!

2023-06-08 11:20 UTC, uknmr commented on src/pages/wiki/documents/braille-keyboard.md
> +## 点字ディスプレイ
点字ディスプレイ = 点字キーボードのイメージがあったかも。

2023-06-09 01:53 UTC, kgsi commented
辻さんにレビュー済

2023-06-09 04:10 UTC, uknmr approved these changes
LGTM~

2023-06-12 07:47 UTC, ysasaki10 reviewed
- 「ブレール（Braille）」の語源
- デジタルデバイスに対応した点字入力
の部分は必要？

2023-06-13 22:43 UTC, uknmr commented
> 「ブレール（Braille）」の語源
デジタルデバイスに対応した点字入力

私はどちらも知らない情報だったので、点字ディスプレイの関連情報として載ってるのは違和感なかったです!

2023-06-14 03:23 UTC, kgsi commented
@ysasaki10 同じく知識としてあまり書いていない情報だったので載せておきたいです

2023-06-16 04:49 UTC, wentzzz approved these changes
lgtm

2023-06-16 06:33 UTC, merged